// Research only. Native engines behind one controlled local service.
// No production adapter, automatic daemon installation, or persistent source cache.
use std::{collections::{HashMap, VecDeque}, env, fs, io::{BufRead, BufReader, Read, Write}, os::unix::{fs::PermissionsExt, net::{UnixListener, UnixStream}}, sync::mpsc, thread, time::Instant};
use serde::Deserialize;
use serde_json::{Value, json};
use tree_sitter_highlight::{HighlightConfiguration, HighlightEvent, Highlighter};
use syntect::{easy::HighlightLines, highlighting::{Color, ScopeSelectors, StyleModifier, Theme, ThemeItem, ThemeSettings}, parsing::SyntaxSet};
use std::str::FromStr;
const COLORS: [u32; 11] = [0xc6c8d1,0xc792ea,0x82aaff,0xffcb6b,0x89ddff,0xf78c6c,0xc3e88d,0xf07178,0x676e95,0xa9c8de,0xff5370];
const ROLES: [&str; 11] = ["plain","keyword","variable","property","function","type","string","number","comment","operator","constant"];
type Spans = Vec<(usize,usize,usize)>;
fn push(out:&mut Spans,a:usize,b:usize,role:usize){if b<=a{return}if let Some(last)=out.last_mut(){if last.1==a&&last.2==role{last.1=b;return}}out.push((a,b,role));}
fn palette_role(rgb:u32)->usize{COLORS.iter().position(|&c|c==rgb).unwrap_or(0)}
fn render(source:&str,spans:&Spans,escapes:&[String])->Result<String,String>{let mut out=String::with_capacity(source.len()*3);let mut end=0;for &(a,b,r) in spans{if a!=end||b>source.len()||!source.is_char_boundary(a)||!source.is_char_boundary(b){return Err("non_exact_source_ranges".into())}out.push_str(&escapes[r]);out.push_str(&source[a..b]);out.push_str("\x1b[39m");end=b;}if end!=source.len(){return Err("non_exact_source_length".into())}Ok(out)}
fn theme()->Theme{let settings=ThemeSettings{foreground:Some(color(COLORS[0])),background:Some(color(0x202020)),..Default::default()};let selectors=["keyword, storage","variable","variable.other.property, entity.other.attribute-name","entity.name.function, support.function","entity.name.type, entity.name.class, support.type, support.class","string","constant.numeric","comment","keyword.operator","constant.language, constant.other"];Theme{name:Some("research".into()),author:None,settings,scopes:selectors.iter().enumerate().map(|(i,s)|ThemeItem{scope:ScopeSelectors::from_str(s).unwrap(),style:StyleModifier{foreground:Some(color(COLORS[i+1])),..Default::default()}}).collect()}}
fn color(c:u32)->Color{Color{r:(c>>16)as u8,g:(c>>8)as u8,b:c as u8,a:255}}
enum Backend{Tree{configs:HashMap<String,HighlightConfiguration>,hi:Highlighter},Syntect{syntaxes:SyntaxSet,theme:Theme},Giallo(giallo::Registry)}
impl Backend{
 fn new(kind:&str,theme_path:&str)->Self{match kind{
 "tree"=>{let ts=format!("{}\n{}",tree_sitter_javascript::HIGHLIGHT_QUERY,tree_sitter_typescript::HIGHLIGHTS_QUERY);let inputs=vec![
 ("typescript",tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into(),ts.as_str(),"",tree_sitter_typescript::LOCALS_QUERY),
 ("python",tree_sitter_python::LANGUAGE.into(),tree_sitter_python::HIGHLIGHTS_QUERY,"",""),
 ("bash",tree_sitter_bash::LANGUAGE.into(),tree_sitter_bash::HIGHLIGHT_QUERY,"",""),
 ("rust",tree_sitter_rust::LANGUAGE.into(),tree_sitter_rust::HIGHLIGHTS_QUERY,tree_sitter_rust::INJECTIONS_QUERY,"")];let configs=inputs.into_iter().map(|(name,lang,highlights,injections,locals)|{let mut cfg=HighlightConfiguration::new(lang,name,highlights,injections,locals).unwrap();cfg.configure(&ROLES);(name.to_owned(),cfg)}).collect();Self::Tree{configs,hi:Highlighter::new()}},
 "syntect"=>{let assets=bat::assets::HighlightingAssets::from_binary();Self::Syntect{syntaxes:assets.get_syntax_set().unwrap().clone(),theme:theme()}},
 "giallo"=>{let mut r=giallo::Registry::builtin().unwrap();r.add_theme_from_path(theme_path).unwrap();r.link_grammars();Self::Giallo(r)},_=>panic!("unknown engine")}}
 fn spans(&mut self,lang:&str,source:&str)->Result<Spans,String>{let mut out=vec![];match self{
 Self::Tree{configs,hi}=>{let cfg=configs.get(lang).ok_or("unsupported_language")?;let mut stack=vec![];let events=hi.highlight(cfg,source.as_bytes(),None,None,|name|configs.get(name)).map_err(|e|format!("{e:?}"))?;for event in events{match event.map_err(|e|format!("{e:?}"))?{HighlightEvent::HighlightStart(h)=>stack.push(h.0),HighlightEvent::HighlightEnd=>{stack.pop();},HighlightEvent::Source{start,end}=>push(&mut out,start,end,*stack.last().unwrap_or(&0))}}},
 Self::Syntect{syntaxes,theme}=>{let ext=match lang{"typescript"=>"ts","python"=>"py","bash"=>"sh","rust"=>"rs",_=>return Err("unsupported_language".into())};let syntax=syntaxes.find_syntax_by_extension(ext).ok_or("unsupported_language")?;let mut h=HighlightLines::new(syntax,theme);let mut at=0;for line in source.split_inclusive('\n'){for (style,text) in h.highlight_line(line,syntaxes).map_err(|e|e.to_string())?{let c=style.foreground;let role=palette_role(((c.r as u32)<<16)|((c.g as u32)<<8)|(c.b as u32));push(&mut out,at,at+text.len(),role);at+=text.len();}}},
 Self::Giallo(r)=>{let lang=if lang=="bash"{"shellscript"}else{lang};let opts=giallo::HighlightOptions::new(lang,giallo::ThemeVariant::Single("research")).merge_whitespace(false).merge_same_style_tokens(true);let highlighted=r.highlight(source,&opts).map_err(|e|e.to_string())?;let mut at=0;for (i,line) in highlighted.tokens.iter().enumerate(){if i>0{if source.as_bytes().get(at)!=Some(&b'\n'){return Err("giallo_normalized_line_endings".into())}push(&mut out,at,at+1,0);at+=1;}for token in line{let giallo::ThemeVariant::Single(style)=&token.style else{return Err("unexpected_dual_theme".into())};if source.get(at..at+token.text.len())!=Some(token.text.as_str()){return Err("giallo_non_exact_source".into())}let hex=style.foreground.as_hex();let rgb=u32::from_str_radix(hex.trim_start_matches('#'),16).map_err(|e|e.to_string())?;push(&mut out,at,at+token.text.len(),palette_role(rgb));at+=token.text.len();}}if source.get(at..)==Some("\n"){push(&mut out,at,at+1,0);at+=1;}if at!=source.len(){return Err("giallo_non_exact_source_length".into())}}
 }Ok(out)}
}
#[derive(Deserialize)]struct Request{id:u64,op:String,#[serde(default)]lang:String,#[serde(default)]source:String,#[serde(default)]cache:bool,#[serde(default)]diagnostic:bool}
struct Service{backend:Backend,escapes:Vec<String>,requests:u64,highlights:u64,hits:u64,cache:VecDeque<(String,String,String)>,cache_bytes:usize}
impl Service{
 fn handle(&mut self,q:Request)->Value{self.requests+=1;if q.op=="stats"{return json!({"id":q.id,"ok":true,"requests":self.requests,"highlights":self.highlights,"cacheHits":self.hits,"cacheEntries":self.cache.len(),"cacheBytes":self.cache_bytes})}if q.op=="echo"{return json!({"id":q.id,"ok":true,"ansi":q.source,"computeNs":0})}if q.op!="highlight"{return json!({"id":q.id,"ok":false,"error":"unsupported_operation"})}if q.source.len()>4*1024*1024{return json!({"id":q.id,"ok":false,"error":"source_too_large"})}
 if q.cache&&!q.diagnostic{if let Some(i)=self.cache.iter().position(|(lang,source,_)|lang==&q.lang&&source==&q.source){self.hits+=1;let entry=self.cache.remove(i).unwrap();let ansi=entry.2.clone();self.cache.push_back(entry);return json!({"id":q.id,"ok":true,"ansi":ansi,"computeNs":0,"cacheHit":true})}}
 let start=Instant::now();self.highlights+=1;let spans=match self.backend.spans(&q.lang,&q.source){Ok(s)=>s,Err(e)=>return json!({"id":q.id,"ok":false,"error":e})};let ansi=match render(&q.source,&spans,&self.escapes){Ok(a)=>a,Err(e)=>return json!({"id":q.id,"ok":false,"error":e})};let elapsed=start.elapsed().as_nanos()as u64;
 if q.cache&&!q.diagnostic{let bytes=q.lang.len()+q.source.len()+ansi.len();if bytes<=16*1024*1024{while self.cache.len()>=64||self.cache_bytes+bytes>16*1024*1024{if let Some((a,b,c))=self.cache.pop_front(){self.cache_bytes-=a.len()+b.len()+c.len();}else{break}}self.cache_bytes+=bytes;self.cache.push_back((q.lang,q.source,ansi.clone()));}}
 let mut response=json!({"id":q.id,"ok":true,"ansi":ansi,"computeNs":elapsed,"cacheHit":false});if q.diagnostic{response["spans"]=json!(spans);response["roles"]=json!(ROLES);}response
 }
}
fn connection(stream:UnixStream,tx:mpsc::SyncSender<(Request,mpsc::SyncSender<Value>)>){let mut writer=stream.try_clone().unwrap();let mut reader=BufReader::new(stream);loop{let mut line=String::new();match reader.by_ref().take(8*1024*1024+1).read_line(&mut line){Ok(0)|Err(_)=>break,Ok(_)if line.len()>8*1024*1024=>break,_=>{}}let q=match serde_json::from_str(&line){Ok(q)=>q,Err(_)=>break};let(reply_tx,reply_rx)=mpsc::sync_channel(1);if tx.send((q,reply_tx)).is_err(){break}let Ok(reply)=reply_rx.recv()else{break};// Serialize a complete frame before touching the socket. Streaming serde directly
// into UnixStream emits many tiny writes for escaped ANSI fragments.
let Ok(mut encoded)=serde_json::to_vec(&reply)else{break};encoded.push(b'\n');if writer.write_all(&encoded).is_err(){break}}}
fn main(){let args:Vec<String>=env::args().collect();let kind=&args[1];let socket=&args[2];let theme_path=&args[3];let start=Instant::now();let backend=Backend::new(kind,theme_path);let initialized_ms=start.elapsed().as_secs_f64()*1000.;let escapes=COLORS.iter().map(|c|format!("\x1b[38;2;{};{};{}m",(c>>16)&255,(c>>8)&255,c&255)).collect();let mut service=Service{backend,escapes,requests:0,highlights:0,hits:0,cache:VecDeque::new(),cache_bytes:0};let listener=UnixListener::bind(socket).unwrap();fs::set_permissions(socket,fs::Permissions::from_mode(0o600)).unwrap();let(tx,rx)=mpsc::sync_channel::<(Request,mpsc::SyncSender<Value>)>(32);thread::spawn(move||for(q,reply)in rx{let answer=service.handle(q);let _=reply.send(answer);});println!("{}",json!({"ready":true,"pid":std::process::id(),"engine":kind,"initializationMs":initialized_ms,"workers":1,"responseBuffering":"one complete NDJSON frame","harnessVersion":2,"cacheLimitBytes":16*1024*1024}));for stream in listener.incoming(){match stream{Ok(stream)=>{let tx=tx.clone();thread::spawn(move||connection(stream,tx));},Err(_)=>break}}}
